### ISSUE TITLE
When You Need to Change the Port, You Need to do it Twice

### ISSUE THREAD

**Issue by ingomohr** [eum2o/planning-poker#7]
When you cannot use the standard port - e.g. app port (5000) and you need to change it, you actually need to do that twice in order to get the app working with the server:

* in `server.js` and
* in `constants.js`

We should have exactly one place to specify that one.

**Comment by eum2o** [comment]
Thanks for submitting the issue! This should be fixed. It's worth noting that the ports also need to be specified in the Dockerfile and when running the Docker container.

**Comment by eum2o** [comment]
This was fixed by using [dotenv](https://www.npmjs.com/package/dotenv). Server and client now share the configuration in the [.env](https://github.com/eum2o/planning-poker/blob/master/.env) file.

The Dockerfile still defines port 3001, but it will override the port defined in the .env file and will not result in a duplicate port.

Note that port 5000 is not used anymore, because the REST endpoint was removed with #2.
